language: java
jdk: openjdk8

sudo: true

bundler_args: --retry 3

script: mvn verify jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN

notifications:
  email:
    on_sucess: never
    on_failure: always